### ISSUE TITLE
Utilize the SFCC-CI Certificate Support For Meta Data Import

### ISSUE THREAD

**Issue by SamiRedVan** [redvanworkshop/autobahn-cli#1]
SFCC staging instances are typically require a p12 key file and associated passphrase to to push and pull files into WebDav's. Example:
**With SFCC-CI Pushing Meta Data and Trigger Import**
```
node cli.js instance:upload ../data/sfra-data.zip -i ${{ secrets.STAGING_SECURE_DOMAIN }} -c ../../.github/certificate/${{ secrets.CERT_FILE }} -p "${{ secrets.CERT_PASS }}"
node cli.js instance:import sfra-data.zip -i ${{ secrets.STAGING_DOMAIN }} -s
```
Note the upload domain is different from the trigger import

**With Autobahn CLI**
```
npx autobahn-cli import --config example.dw.json --data-final attribute_groups --hostname ${{ secrets.DEVELOPMENT_DOMAIN }} --client-id ${{ secrets.API_CLIENT }} --client-secret ${{ secrets.API_CLIENT_SECRET }}
```
I imagine the following options:
- "--secure-hostname" alternate url
- "--certificate-keyfile" filename
- "--certificate-passphrase" String

Also I think utilizing the example.dw.json file to pass this info would be useful and consistent with the current setup.

**Comment by z1haze** [comment]
Sounds good, I can do this. Just a FYI though, we should not be storing the certificates in the repo like this. A potential major security issue. eg `-c ../../.github/certificate/${{ secrets.CERT_FILE }} -p "${{ secrets.CERT_PASS }}"`.

What I have done in the past is encode the cert in an env var and then decode it in the workflow with something like this:
`echo $STAGING_WEBDAV_CERT | base64 --decode >> cert.pem`

**Comment by z1haze** [comment]
FWIW, I wrote a shell script years ago to handle deployments, before all these fancy sfcc libs were a thing, and it basically uses the same process as described above (secure data in env vars).

`/dw/dwdeploy.sh -z ${BITBUCKET_CLONE_DIR}/cartridges.zip -h $STAGING_WEBDAV_HOST -u $STAGING_WEBDAV_USER -p $STAGING_WEBDAV_PASS -v $CODE_VERSION -c ${BITBUCKET_CLONE_DIR}/cert.pem -x $STAGING_WEBDAV_CERT_PASS`

https://github.com/z1haze/dw-deploy/blob/master/dwdeploy.sh

**Comment by z1haze** [comment]
Sounds like this is not needed after all? @zseeling @SamiRedVan
